# Generated by Django 4.0.6 on 2022-07-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
